### ISSUE TITLE
0 error:--shape-attr: At Most 10 required but received 16

### ISSUE THREAD

**Issue by falconlulu** [Esri/cityengine-sdk#40]
This bug appeared when I had more than 10 -a parameters. Why is there a limit of 10. There may be many shape attrs for a cga file

**Comment by mistafunk** [comment]
Thanks for the heads up, we'll try to improve this.

In the meantime, try to increase the value 10 here:
https://github.com/Esri/cityengine-sdk/blob/cf2ae19ad2cd09dc9821af1e52cfa4df35c775a4/examples/prt4cmd/src/utils.cpp#L256
