### ISSUE TITLE
`prt4cmd.exe` fails to load `com.esri.prt.unreal.dll` 

### ISSUE THREAD

**Issue by OlivierSohn** [Esri/cityengine-sdk#51]
Hello,

While following the [README_windows](https://github.com/Esri/cityengine-sdk/blob/main/examples/prt4cmd/README_windows.md), for the command:

```
C:\cityengine-sdk\examples\prt4cmd\install>bin\prt4cmd.exe -l 3 -g ..\..\..\data\candler_footprint.obj -p ..\..\..\data\candler.rpk -a ruleFile:string=bin/candler.cgb -a startRule:string=Default$Footprint -e com.esri.prt.codecs.OBJEncoder -z baseName:string=theCandler
```

the following error occured : 

```
[2022-11-10 13:51:11] [error] failed to load library: error while loading library 'C:\cityengine-sdk\examples\prt4cmd\install\lib\com.esri.prt.unreal.dll': The specified module could not be found.
[2022-11-10 13:51:11] [warning] Failed to load library 'C:\cityengine-sdk\examples\prt4cmd\install\lib\com.esri.prt.unreal.dll' as extension for PRT core at 'C:\cityengine-sdk\examples\prt4cmd\install\bin\com.esri.prt.core.dll'
[2022-11-10 13:51:11] [warning] CGB file contains warning 'Potentially problematic CGAC version 1.6 : recompiling with current CGA Compiler (1.19) is recommended.'
```

Removing `com.esri.prt.unreal.dll` in `examples\prt4cmd\install\lib `fixed the error. Note that I don't have Unreal Engine installed on my machine.

Thanks,
Olivier

**Comment by mistafunk** [comment]
Thanks for the feedback. We recognize that this error message is somewhat misleading. If you do not need the Unreal encoder for your task then this error can be ignored - or - you might want to install the Epic launcher which will install the necessary runtime dependencies for our Unreal encoder dll.

**Comment by OlivierSohn** [comment]
> this error can be ignored, prt4cmd will still work correctly

Unfortunately it prevents prt4cmd from working correctly, this is why the dll *must* be removed in my case. This is somewhat hard to figure out for new users.

**Comment by mistafunk** [comment]
Ok, that is unexpected. We will look into it asap.

**Comment by mistafunk** [comment]
Actually, one more question: you are seeing that when the unreal encoder cannot be loaded, you will not get the expected OBJ file in the output folder, correct?

**Comment by OlivierSohn** [comment]
My bad, actually the tool produces results in case the dll failed to load.

**Comment by OlivierSohn** [comment]
Maybe this error message should be made a warning instead?

**Comment by OlivierSohn** [comment]
Also the "output" directory is actually inside the install directory, not next to the install directory contrary to what the doc says:

> The result is placed in a new output directory next to the install directory

This adds to the confusion because when looking for this folder at the location the doc specifies, nothing is there.

Maybe a success message in the tool saying where the results have been written would be useful.

**Comment by mistafunk** [comment]
> Maybe this error message should be made a warning instead?

Agreed - the error on the first line is actually the underlying issue, while the second line with the warning is the main message to the user. We'll try to demote the error to a warning as well (or merge the two).

**Comment by OlivierSohn** [comment]
Ah ok, makes sense.
