### ISSUE TITLE
How to complete shapefile to road Shape?

### ISSUE THREAD

**Issue by white500** [Esri/cityengine-sdk#65]
Hi,
I want to use the sdk to generate a road model. My raw data is a shapefile with the suffix ".shp". I know how to get the data in the shpfile, but I can't convert the lines in the shapefile into the required vertexCoords parameters. How is this process done, in which direction should I inquire, can you provide some cases in this regard, thank you very much!

**Comment by mistafunk** [comment]
Hi & thanks for your interest in our SDK.

Let me ask a few questions to better understand your situation:
* I assume you read the shapefile and want to use `prt::InitialShapeBuilder` for each feature to create a `prt::InitialShape` and then run a RPK on it, correct?
* Which library do you use to read the shapefile?
* Which feature type do you want to read (lines, polygons, ...)?
* What do you mean exactly with "I can't convert the lines"?

Best,
Simon

**Comment by white500** [comment]
Thank you for your reply. Here is my answer:
1. yes
2. gdal
3. lines
4. I want to generate roads using rpk rules

The official example is not road network example, or is the sdk only able to generate buildings.

I want to convert the line data in.shp to the data in the image. Can I do that?
![model](https://github.com/Esri/cityengine-sdk/assets/37032819/3153ea09-29ee-436a-9593-d4e12c2c47eb)

**Comment by mistafunk** [comment]
The algorithm which creates the street shapes (i.e. the input geometry for the procedural rules) from center lines is not part of the CityEngine SDK (PRT), it is part of the CityEngine desktop app itself.

To generate road models with CE SDK (PRT) you would need to export the "start" shapes (as you have them in above screenshot) created by CityEngine (including UV coordinates). Then you read this geo in your app, assign the corresponding RPK and generate.

**Comment by white500** [comment]
Should I use the export wavefront obj
![image](https://github.com/Esri/cityengine-sdk/assets/37032819/ed5bbe31-bc4a-4e17-9432-9bcaa67e3ad3)

**Comment by white500** [comment]
Thanks for your reply. I'll try

**Comment by mistafunk** [comment]
Closing this for now - feel free to reopen in case there are problems.
